### ISSUE TITLE
Errors in Feed

### ISSUE THREAD

**Issue by g-gundam** [dm13450/dm13450.github.io#24]
https://dm13450.github.io/feed.xml

Chromium-based browsers complain about encoding:
![image](https://github.com/dm13450/dm13450.github.io/assets/9591914/9604bfa6-11fe-4b43-acd3-63cd85632dd7)

Firefox-based browsers complain about the XML not being well-formed:
![image](https://github.com/dm13450/dm13450.github.io/assets/9591914/edd674fd-dbcc-4162-a3af-ecfe26922015)

The latter might be more serious.  It may be preventing feed readers from parsing your feed.  In my own case, [Emacs' newsticker](https://www.emacswiki.org/emacs/NewsTicker) can't parse this feed.

**Comment by dm13450** [comment]
Dodgy characters in one of my posts. Should be ok now

**Comment by g-gundam** [comment]
It looks good, and your content shows up in my feed reader now.  Thanks for fixing that.
